### ISSUE TITLE
Plugin created BG layer doesn't have "radius" option.

### ISSUE THREAD

**Issue by evosyn** [ddwht/sketch-dynamic-button#14]
![screen shot 2015-04-15 at 10 04 21 am](https://cloud.githubusercontent.com/assets/9837158/7161820/b19ca47e-e356-11e4-875a-249d2149257c.png)

**Comment by kellyxu2014** [comment]
I have the same issue, bg radius doesn't show up in Sketch 3.3

**Comment by yosefw** [comment]
+1

**Comment by ddwht** [comment]
Thanks for feedback. Now this bug was fixed.

**Comment by kellyxu2014** [comment]
works now, thank you!

**Comment by yosefw** [comment]
Thanks man :-)
