### ISSUE TITLE
Icon to the right of text

### ISSUE THREAD

**Issue by larsenpedersen** [ddwht/sketch-dynamic-button#31]
I'm trying to create a dynamic tag like this:

<img width="669" alt="screen shot 2016-03-05 at 12 50 01" src="https://cloud.githubusercontent.com/assets/1841598/13547388/2ad4f786-e2d1-11e5-8b97-f826d56d0fe7.png">

The "x" (icon) is suppose to be a delete button.

How can I still make this dynamic without having to move the icon all the time?

**Comment by mludowise** [comment]
Try the Sketch Relabel Button, it has the behavior you're looking for:
https://github.com/kenmoore/sketch-relabel-button

**Comment by larsenpedersen** [comment]
@mludowise Thanks a bunch!
