### ISSUE TITLE
[SUGGESTION] Apply to symbols in Sketch 3.7

### ISSUE THREAD

**Issue by ziyafenn** [ddwht/sketch-dynamic-button#33]
With new feature of Sketch 3.7, when text label of symbol can be changed without editing symbol itself, would be amazing to apply dynamic button to this symbol, so it changes size of button/symbol without touching original symbol itself! Don't know how hard is to do, but just in case will leave this wish here.

Thanks a lot for the amazing plugin!

**Comment by fuggfuggfugg** [comment]
@Katalonian , Can you simplify the above? 

Sorry I'm not up-to date with the new 3.7 feature so I'm having a hard time understanding this. If I understand correctly, maybe I can give it a shot. [I have an updated dynamic button plugin.](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5)

**Comment by samuelorf** [comment]
I would like to elaborate on this feature request. In 3.7 Sketch has overrides in symbols. Overrides allow you to have multiple instances of a symbol but change elements limited to text and graphics. It would be really nice if you could update the text in an override say to a longer text button and the background padding would change dynamically.

Thanks for the rad plugin.

**Comment by nedzen** [comment]
this is no longer necessary since in the last verssion of sketch you can use the new resizing properties. see this thread [here](https://sketchtalk.io/discussion/comment/2612/#Comment_2612)

**Comment by anandmehrotra** [comment]
@Katalonian @samuelorf @nedzen 

Still in a branch and may have issues but I think this will work with Symbols. Please try and give feedback. 

https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/tree/sketch-symbols-fuck-yeah

**Comment by fuggfuggfugg** [comment]
@Katalonian @samuelorf @nedzen 

Still in a branch and may have issues but I think this will work with Symbols. Please try and give feedback. 

https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/tree/sketch-symbols-fuck-yeah

**Comment by ziyafenn** [comment]
Thanks, seems to be working good!

**Comment by fuggfuggfugg** [comment]
I'm so glad! Thanks for testing it out for me. 
If you come across an issue, please log a bug here https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/issues/19
